### ISSUE TITLE
Add documentation to this awesome project.

### ISSUE THREAD

**Issue by Localhost422** [getbannerman/babl#1]
Your project seems really interesting.

I'd like to use it for my personal project but it's seems there is no documentation.

Would that be possible to add documentation to this project?

**Comment by fterrazzoni** [comment]
Documentation will be available soon :-)

**Comment by fterrazzoni** [comment]
I added some documentation. Not sure if it's enough to get started alone, but it is certainly better than nothing at all.

More pages will come later!
